
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import WelcomeView from '@/components/welcomeView/welcome-view'
import About from '@/components/AboutMeBanner/about'
import SkillsSection from '@/components/Skills/skills'
import Project from '@/components/projects/projects'
import Contact from '@/components/contact/contact'
import Lenis from '@studio-freight/lenis'
import { useMotionValue, useSpring , motion} from 'framer-motion'
import { useEffect } from 'react'

import Footer from '@/components/footer/footer'





export default function Home() {

  

  useEffect(() =>{
    const lenis = new Lenis()


function raf(time) {
  lenis.raf(time)
  requestAnimationFrame(raf)
}

requestAnimationFrame(raf)
  })


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
     
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <WelcomeView/>
        <About/>
      
        <SkillsSection/>
        <Project/>
        <Contact/>
        {/* <Footer/> */}
      </main>
    </>
  )
}
